#!/usr/bin/env bash

# Login to docker.io
#echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker logout
echo "$DOCKER_PASSWORD" | podman login -u "$DOCKER_USERNAME" --password-stdin

# push the image
podman push --format=docker ${IMAGE_NAMESPACE}/${IMAGE_NAME}:${CONTAINER_DISTRO}

# push alternate tag if available
if ! [ -z $IMAGE_ALTERNATE_TAG ]; then
  podman tag ${IMAGE_NAMESPACE}/${IMAGE_NAME}:${CONTAINER_DISTRO} ${IMAGE_NAMESPACE}/${IMAGE_NAME}:${IMAGE_ALTERNATE_TAG}
  podman push --format=docker ${IMAGE_NAMESPACE}/${IMAGE_NAME}:${IMAGE_ALTERNATE_TAG}
fi

# Logout from docker.io
podman logout
